# Generated by Django 5.1.6 on 2025-02-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_contact_name_alter_contact_phone_task_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='task',
            new_name='subtask',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(to='api_app.contact'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Technical Task', 'Technical Task'), ('User Story', 'User Story')], default='Technical Task', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
