# Generated by Django 5.1.6 on 2025-02-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_rename_task_subtask_subtask_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='subtask',
            new_name='task',
        ),
    ]
