# Generated by Django 5.1.6 on 2025-02-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_alter_task_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assignedTo',
        ),
    ]
