# Generated by Django 5.1.6 on 2025-02-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_rename_assigned_to_task_assignedto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='dueDate',
        ),
    ]
